# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EnvironmentalETL
                                 A QGIS plugin
 Environmental exposure ETL plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-12
        copyright            : (C) 2026 by Praveenkumar Saminathan
        email                : praveennathan10@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EnvironmentalETL class from file EnvironmentalETL.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .EnvironmentalETL import EnvironmentalETL
    return EnvironmentalETL(iface)
