# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EnvironmentalETL
                                 A QGIS plugin
 Environmental exposure ETL plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-12
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Praveenkumar Saminathan
        email                : praveennathan10@gmail.com
 ***************************************************************************/
/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .EnvironmentalETL_dialog import EnvironmentalETLDialog
import os


class EnvironmentalETL:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'EnvironmentalETL_{}.qm'.format(locale))
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)
        self.actions = []
        self.menu = self.tr(u'&EnvironmentalETL')
        self.first_start = None

    def tr(self, message):
        return QCoreApplication.translate('EnvironmentalETL', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)
        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)
        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = ':/plugins/EnvironmentalETL/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Environmental ETL'),
            callback=self.run,
            parent=self.iface.mainWindow())
        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&EnvironmentalETL'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create dialog only once
        if self.first_start == True:
            self.first_start = False
            self.dlg = EnvironmentalETLDialog()
            self.dlg.setWindowTitle("Environmental ETL - ERA5 Exposure Tool")
            from qgis.PyQt.QtCore import QDate
            self.dlg.dateFrom.setDisplayFormat("MM/dd/yyyy")
            self.dlg.dateTo.setDisplayFormat("MM/dd/yyyy")
            self.dlg.dateFrom.setCalendarPopup(True)
            self.dlg.dateTo.setCalendarPopup(True)
            start_date = QDate(1940, 1, 1)
            self.dlg.dateFrom.setMinimumDate(start_date)
            self.dlg.dateTo.setMinimumDate(start_date)
            today = QDate.currentDate()
            self.dlg.dateFrom.setDate(today)
            self.dlg.dateTo.setDate(today)

            # ── NEW: mutual exclusivity between comboTime and comboDailyStat ──
            def on_time_changed(idx):
                if idx > 0:  # user picked a real time step
                    self.dlg.comboDailyStat.blockSignals(True)
                    self.dlg.comboDailyStat.setCurrentIndex(0)
                    self.dlg.comboDailyStat.blockSignals(False)

            def on_stat_changed(idx):
                if idx > 0:  # user picked a daily stat
                    self.dlg.comboTime.blockSignals(True)
                    self.dlg.comboTime.setCurrentIndex(0)
                    self.dlg.comboTime.blockSignals(False)

            self.dlg.comboTime.currentIndexChanged.connect(on_time_changed)
            self.dlg.comboDailyStat.currentIndexChanged.connect(on_stat_changed)

        # Show dialog — repopulate every time
        from qgis.core import QgsProject
        self.dlg.comboLayer.clear()
        self.dlg.comboLayer.addItem("Select Polygon Layer")
        for layer in QgsProject.instance().mapLayers().values():
            self.dlg.comboLayer.addItem(layer.name())

        self.dlg.comboVariable.clear()
        self.dlg.comboVariable.addItem("Choose Variable")
        self.dlg.comboVariable.addItem("2m Temperature")
        self.dlg.comboVariable.addItem("Total Precipitation")
        self.dlg.comboVariable.addItem("Surface Pressure")

        self.dlg.comboMethod.clear()
        self.dlg.comboMethod.addItem("Choose Method")
        self.dlg.comboMethod.addItem("Centroid")
        self.dlg.comboMethod.addItem("Point-based Averaging (Polygon Mean)")
        self.dlg.comboMethod.addItem("Area-weighted Averaging")

        self.dlg.comboTime.clear()
        self.dlg.comboTime.addItem("Choose Time")
        self.dlg.comboTime.addItems([
            "00:00", "01:00", "02:00", "03:00", "04:00", "05:00",
            "06:00", "07:00", "08:00", "09:00", "10:00", "11:00",
            "12:00", "13:00", "14:00", "15:00", "16:00", "17:00",
            "18:00", "19:00", "20:00", "21:00", "22:00", "23:00"
        ])

        # ── NEW: populate comboDailyStat ──────────────────────────────────
        self.dlg.comboDailyStat.clear()
        self.dlg.comboDailyStat.addItem("Choose Daily Stat")
        self.dlg.comboDailyStat.addItem("Daily Min")
        self.dlg.comboDailyStat.addItem("Daily Max")
        self.dlg.comboDailyStat.addItem("Daily Mean")

        self.dlg.show()
        result = self.dlg.exec_()

        if result:
            from .etl_engine import download_era5, run_etl

            layer = self.dlg.comboLayer.currentText()
            if layer == "Select Polygon Layer":
                self.iface.messageBar().pushMessage(
                    "Error", "Please select a polygon layer", level=2, duration=5)
                return

            from qgis.core import QgsProject
            selected_layer = None
            for l in QgsProject.instance().mapLayers().values():
                if l.name() == layer:
                    selected_layer = l
            if selected_layer is None:
                return

            shapefile_path = selected_layer.source()

            variable_text = self.dlg.comboVariable.currentText()
            if variable_text == "2m Temperature":
                variable = "2m_temperature"
            elif variable_text == "Total Precipitation":
                variable = "total_precipitation"
            elif variable_text == "Surface Pressure":
                variable = "surface_pressure"
            else:
                self.iface.messageBar().pushMessage(
                    "Error", "Please choose a variable", level=2, duration=5)
                return

            date_from = self.dlg.dateFrom.date().toString("yyyy-MM-dd")
            date_to   = self.dlg.dateTo.date().toString("yyyy-MM-dd")
            if date_from > date_to:
                self.iface.messageBar().pushMessage(
                    "Error", "Start date must be before end date", level=2, duration=5)
                return

            method_text = self.dlg.comboMethod.currentText()
            if method_text == "Centroid":
                method = "centroid"
            elif method_text == "Point-based Averaging (Polygon Mean)":
                method = "gridmean"
            elif method_text == "Area-weighted Averaging":
                method = "weighted"
            else:
                self.iface.messageBar().pushMessage(
                    "Error", "Please choose a method", level=2, duration=5)
                return

            # ── NEW: determine time_selected from whichever combo is set ──
            time_selected   = self.dlg.comboTime.currentText()
            daily_stat_text = self.dlg.comboDailyStat.currentText()

            has_time = time_selected not in ("Choose Time", "")
            has_stat = daily_stat_text not in ("Choose Daily Stat", "")

            if not has_time and not has_stat:
                self.iface.messageBar().pushMessage(
                    "Error",
                    "Please choose a time step OR a daily statistic (Min / Max / Mean)",
                    level=2,
                    duration=5
                )
                return

            # If daily stat is chosen it overrides the time step
            if has_stat:
                time_selected = daily_stat_text   # e.g. "Daily Min"

            # ── (unchanged) bounding box computation ─────────────────────
            from qgis.core import QgsFeatureRequest
            minx = float("inf")
            miny = float("inf")
            maxx = float("-inf")
            maxy = float("-inf")
            for f in selected_layer.getFeatures():
                geom = f.geometry().boundingBox()
                minx = min(minx, geom.xMinimum())
                miny = min(miny, geom.yMinimum())
                maxx = max(maxx, geom.xMaximum())
                maxy = max(maxy, geom.yMaximum())

            from qgis.core import (QgsCoordinateReferenceSystem,
                                   QgsCoordinateTransform,
                                   QgsProject, QgsRectangle)
            source_crs = selected_layer.crs()
            target_crs = QgsCoordinateReferenceSystem("EPSG:4326")
            rect = QgsRectangle(minx, miny, maxx, maxy)
            if source_crs != target_crs:
                transform = QgsCoordinateTransform(
                    source_crs, target_crs, QgsProject.instance())
                rect = transform.transformBoundingBox(rect)
            minx = rect.xMinimum()
            miny = rect.yMinimum()
            maxx = rect.xMaximum()
            maxy = rect.yMaximum()

            import math
            grid = 0.25
            west  = math.floor((minx + 180) / grid) * grid - 180
            east  = math.ceil( (maxx + 180) / grid) * grid - 180
            south = math.floor((miny + 90)  / grid) * grid - 90
            north = math.ceil( (maxy + 90)  / grid) * grid - 90
            west  -= grid
            east  += grid
            south -= grid
            north += grid

            # ── Run ETL (time_selected now carries hour OR stat name) ─────
            result_df = run_etl(
                shapefile_path,
                variable,
                date_from,
                date_to,
                time_selected,
                self.plugin_dir,
                method=method
            )

            from datetime import datetime
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            var_name = variable
            output_csv = os.path.join(
                self.plugin_dir,
                f"output_{var_name}_{timestamp}.csv"
            )
            result_df.to_csv(output_csv, index=False)

            from qgis.core import QgsVectorLayer, QgsProject
            shape_name = selected_layer.name()
            layer_name = f"ERA5_{var_name}_{shape_name}"
            csv_layer = QgsVectorLayer(output_csv, layer_name, "ogr")
            if csv_layer.isValid():
                QgsProject.instance().addMapLayer(csv_layer)

            self.iface.messageBar().pushMessage(
                "EnvironmentalETL",
                f"ETL completed. Output saved to: {output_csv}",
                level=0,
                duration=5
            )